### ISSUE TITLE
sysrc refuses to accept sysctl declarations

### ISSUE THREAD

**Issue by smyru** [adriaandegroot/FreeBSDTools#5]
With the integration of fixes for bug [187461 - sysrc(8) mishandles variable names containing a dot](https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=187461) - I believe - [line 140](https://github.com/adriaandegroot/FreeBSDTools/blob/master/bin/instant-workstation#L140) will fail to update sysctl.conf and make the KDE settings permanent.

**Comment by adriaandegroot** [comment]
I only hit this once I updated to 13-CURRENT, and it's already fixed in 6b6986d16eb22cdf1a40923f51dcda3249037967 -- since sysrc is for things that are actually shell, and sysconf has not materialized, it's back to `echo >>` (which will append duplicates, but this is a thing to run once, IMO)
